// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from "@prisma/orm-postgres/adapter/operation-types";
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from "@prisma/orm-postgres/target/codec-types";

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from "@prisma/orm-postgres/family-contract/types";
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from "@prisma/orm-postgres/contract/types";

export type StorageHash =
  StorageHashBase<"4d022ac0cb0f4bf62c4e0be712f34f1171c238c4505050d1f1e0d133e117f771">;
export type ExecutionHash =
  ExecutionHashBase<"2a46a1697980a4854f9c9cd7515802a76bcf2e79a304bffcbc281c52de9773b6">;
export type ProfileHash =
  ProfileHashBase<"3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2">;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly "pg/float@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/float4@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/float8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int8number@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/interval@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/numeric@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/time-string@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/time-temporal@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/unboundedint@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "sql/float@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "pg/float8@1"; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly "pg/int@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/int8number@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/numeric@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/unboundedint@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: "pg/int8number@1"; readonly nullable: false };
    readonly anyInput: { readonly output: "pg/int8number@1"; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: "pg/int8@1"; readonly nullable: false };
    readonly anyInput: { readonly output: "pg/int8@1"; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly "pg/char@1": { readonly output: "pg/char@1"; readonly nullable: true };
      readonly "pg/date-string@1": { readonly output: "pg/date-string@1"; readonly nullable: true };
      readonly "pg/date-temporal@1": {
        readonly output: "pg/date-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/enum@1": { readonly output: "pg/enum@1"; readonly nullable: true };
      readonly "pg/float@1": { readonly output: "pg/float@1"; readonly nullable: true };
      readonly "pg/float4@1": { readonly output: "pg/float4@1"; readonly nullable: true };
      readonly "pg/float8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/inet@1": { readonly output: "pg/inet@1"; readonly nullable: true };
      readonly "pg/int@1": { readonly output: "pg/int@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/int2@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/int4@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/int8@1"; readonly nullable: true };
      readonly "pg/int8number@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/interval@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/numeric@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/text-array@1": { readonly output: "pg/text-array@1"; readonly nullable: true };
      readonly "pg/text@1": { readonly output: "pg/text@1"; readonly nullable: true };
      readonly "pg/time-string@1": { readonly output: "pg/time-string@1"; readonly nullable: true };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/time-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-string@1": {
        readonly output: "pg/timestamp-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-temporal@1": {
        readonly output: "pg/timestamp-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-string@1": {
        readonly output: "pg/timestamptz-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-temporal@1": {
        readonly output: "pg/timestamptz-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timetz@1": { readonly output: "pg/timetz@1"; readonly nullable: true };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/varchar@1": { readonly output: "pg/text@1"; readonly nullable: true };
      readonly "sql/char@1": { readonly output: "sql/char@1"; readonly nullable: true };
      readonly "sql/float@1": { readonly output: "sql/float@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "sql/int@1"; readonly nullable: true };
      readonly "sql/text@1": { readonly output: "sql/text@1"; readonly nullable: true };
      readonly "sql/varchar@1": { readonly output: "pg/text@1"; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly "pg/char@1": { readonly output: "pg/char@1"; readonly nullable: true };
      readonly "pg/date-string@1": { readonly output: "pg/date-string@1"; readonly nullable: true };
      readonly "pg/date-temporal@1": {
        readonly output: "pg/date-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/enum@1": { readonly output: "pg/enum@1"; readonly nullable: true };
      readonly "pg/float@1": { readonly output: "pg/float@1"; readonly nullable: true };
      readonly "pg/float4@1": { readonly output: "pg/float4@1"; readonly nullable: true };
      readonly "pg/float8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/inet@1": { readonly output: "pg/inet@1"; readonly nullable: true };
      readonly "pg/int@1": { readonly output: "pg/int@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/int2@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/int4@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/int8@1"; readonly nullable: true };
      readonly "pg/int8number@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/interval@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/numeric@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/text-array@1": { readonly output: "pg/text-array@1"; readonly nullable: true };
      readonly "pg/text@1": { readonly output: "pg/text@1"; readonly nullable: true };
      readonly "pg/time-string@1": { readonly output: "pg/time-string@1"; readonly nullable: true };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/time-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-string@1": {
        readonly output: "pg/timestamp-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-temporal@1": {
        readonly output: "pg/timestamp-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-string@1": {
        readonly output: "pg/timestamptz-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-temporal@1": {
        readonly output: "pg/timestamptz-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timetz@1": { readonly output: "pg/timetz@1"; readonly nullable: true };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/varchar@1": { readonly output: "pg/text@1"; readonly nullable: true };
      readonly "sql/char@1": { readonly output: "sql/char@1"; readonly nullable: true };
      readonly "sql/float@1": { readonly output: "sql/float@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "sql/int@1"; readonly nullable: true };
      readonly "sql/text@1": { readonly output: "sql/text@1"; readonly nullable: true };
      readonly "sql/varchar@1": { readonly output: "pg/text@1"; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly "pg/float@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/float4@1": { readonly output: "pg/float4@1"; readonly nullable: true };
      readonly "pg/float8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/int8number@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/interval@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/numeric@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/time-string@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/time-temporal@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly "pg/int@1": { readonly output: "pg/int8@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/int8@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/int8@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/unboundedint@1"; readonly nullable: true };
      readonly "pg/int8number@1": { readonly output: "pg/unboundedint@1"; readonly nullable: true };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": { readonly output: "pg/int8@1"; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]["json"]
    ? Encoded
    : CodecTypes[CodecId]["json"]
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Application: {
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly userId: CodecTypes["pg/text@1"]["output"];
      readonly jobId: CodecTypes["pg/text@1"]["output"];
      readonly yearsOfExperience: CodecTypes["pg/int4@1"]["output"] | null;
      readonly education: CodecTypes["pg/text@1"]["output"] | null;
      readonly currentCompany: CodecTypes["pg/text@1"]["output"] | null;
      readonly currentRole: CodecTypes["pg/text@1"]["output"] | null;
      readonly expectedSalary: CodecTypes["pg/int4@1"]["output"] | null;
      readonly noticePeriodDays: CodecTypes["pg/int4@1"]["output"] | null;
      readonly skills: ReadonlyArray<CodecTypes["pg/text@1"]["output"]>;
      readonly status: "APPLIED" | "REVIEWING" | "REJECTED" | "ACCEPTED";
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    };
    readonly CandidateProfile: {
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly userId: CodecTypes["pg/text@1"]["output"];
      readonly phone: CodecTypes["pg/text@1"]["output"];
      readonly education: CodecTypes["pg/text@1"]["output"];
      readonly yearsOfExperience: CodecTypes["pg/int4@1"]["output"];
      readonly currentCompany: CodecTypes["pg/text@1"]["output"] | null;
      readonly currentRole: CodecTypes["pg/text@1"]["output"] | null;
      readonly expectedSalary: CodecTypes["pg/int4@1"]["output"];
      readonly noticePeriodDays: CodecTypes["pg/int4@1"]["output"];
      readonly skills: ReadonlyArray<CodecTypes["pg/text@1"]["output"]>;
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    };
    readonly Job: {
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly title: CodecTypes["pg/text@1"]["output"];
      readonly description: CodecTypes["pg/text@1"]["output"];
      readonly company: CodecTypes["pg/text@1"]["output"];
      readonly location: CodecTypes["pg/text@1"]["output"];
      readonly workplaceType: "ON_SITE" | "REMOTE" | "HYBRID";
      readonly category:
        | "ENGINEERING"
        | "DESIGN"
        | "MARKETING"
        | "SALES"
        | "FINANCE"
        | "HUMAN_RESOURCES"
        | "CUSTOMER_SUPPORT"
        | "OPERATIONS";
      readonly experienceLevel: "ENTRY" | "MID" | "SENIOR";
      readonly skills: ReadonlyArray<CodecTypes["pg/text@1"]["output"]>;
      readonly status: "DRAFT" | "PUBLISHED" | "CLOSED";
      readonly isFeatured: CodecTypes["pg/bool@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    };
    readonly RefreshToken: {
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly tokenHash: CodecTypes["pg/text@1"]["output"];
      readonly userId: CodecTypes["pg/text@1"]["output"];
      readonly expiresAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly revokedAt: CodecTypes["pg/timestamptz-string@1"]["output"] | null;
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    };
    readonly User: {
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly email: CodecTypes["pg/text@1"]["output"];
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly passwordHash: CodecTypes["pg/text@1"]["output"];
      readonly role: "USER" | "ADMIN";
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Application: {
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly userId: CodecTypes["pg/text@1"]["input"];
      readonly jobId: CodecTypes["pg/text@1"]["input"];
      readonly yearsOfExperience: CodecTypes["pg/int4@1"]["input"] | null;
      readonly education: CodecTypes["pg/text@1"]["input"] | null;
      readonly currentCompany: CodecTypes["pg/text@1"]["input"] | null;
      readonly currentRole: CodecTypes["pg/text@1"]["input"] | null;
      readonly expectedSalary: CodecTypes["pg/int4@1"]["input"] | null;
      readonly noticePeriodDays: CodecTypes["pg/int4@1"]["input"] | null;
      readonly skills: ReadonlyArray<CodecTypes["pg/text@1"]["input"]>;
      readonly status: "APPLIED" | "REVIEWING" | "REJECTED" | "ACCEPTED";
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
    };
    readonly CandidateProfile: {
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly userId: CodecTypes["pg/text@1"]["input"];
      readonly phone: CodecTypes["pg/text@1"]["input"];
      readonly education: CodecTypes["pg/text@1"]["input"];
      readonly yearsOfExperience: CodecTypes["pg/int4@1"]["input"];
      readonly currentCompany: CodecTypes["pg/text@1"]["input"] | null;
      readonly currentRole: CodecTypes["pg/text@1"]["input"] | null;
      readonly expectedSalary: CodecTypes["pg/int4@1"]["input"];
      readonly noticePeriodDays: CodecTypes["pg/int4@1"]["input"];
      readonly skills: ReadonlyArray<CodecTypes["pg/text@1"]["input"]>;
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
    };
    readonly Job: {
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly title: CodecTypes["pg/text@1"]["input"];
      readonly description: CodecTypes["pg/text@1"]["input"];
      readonly company: CodecTypes["pg/text@1"]["input"];
      readonly location: CodecTypes["pg/text@1"]["input"];
      readonly workplaceType: "ON_SITE" | "REMOTE" | "HYBRID";
      readonly category:
        | "ENGINEERING"
        | "DESIGN"
        | "MARKETING"
        | "SALES"
        | "FINANCE"
        | "HUMAN_RESOURCES"
        | "CUSTOMER_SUPPORT"
        | "OPERATIONS";
      readonly experienceLevel: "ENTRY" | "MID" | "SENIOR";
      readonly skills: ReadonlyArray<CodecTypes["pg/text@1"]["input"]>;
      readonly status: "DRAFT" | "PUBLISHED" | "CLOSED";
      readonly isFeatured: CodecTypes["pg/bool@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
    };
    readonly RefreshToken: {
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly tokenHash: CodecTypes["pg/text@1"]["input"];
      readonly userId: CodecTypes["pg/text@1"]["input"];
      readonly expiresAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly revokedAt: CodecTypes["pg/timestamptz-string@1"]["input"] | null;
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
    };
    readonly User: {
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly email: CodecTypes["pg/text@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly passwordHash: CodecTypes["pg/text@1"]["input"];
      readonly role: "USER" | "ADMIN";
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly application: {
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly currentCompany: CodecTypes["pg/text@1"]["output"] | null;
      readonly currentRole: CodecTypes["pg/text@1"]["output"] | null;
      readonly education: CodecTypes["pg/text@1"]["output"] | null;
      readonly expectedSalary: CodecTypes["pg/int4@1"]["output"] | null;
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly jobId: CodecTypes["pg/text@1"]["output"];
      readonly noticePeriodDays: CodecTypes["pg/int4@1"]["output"] | null;
      readonly skills: ReadonlyArray<CodecTypes["pg/text@1"]["output"]>;
      readonly status: "APPLIED" | "REVIEWING" | "REJECTED" | "ACCEPTED";
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly userId: CodecTypes["pg/text@1"]["output"];
      readonly yearsOfExperience: CodecTypes["pg/int4@1"]["output"] | null;
    };
    readonly candidateProfile: {
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly currentCompany: CodecTypes["pg/text@1"]["output"] | null;
      readonly currentRole: CodecTypes["pg/text@1"]["output"] | null;
      readonly education: CodecTypes["pg/text@1"]["output"];
      readonly expectedSalary: CodecTypes["pg/int4@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly noticePeriodDays: CodecTypes["pg/int4@1"]["output"];
      readonly phone: CodecTypes["pg/text@1"]["output"];
      readonly skills: ReadonlyArray<CodecTypes["pg/text@1"]["output"]>;
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly userId: CodecTypes["pg/text@1"]["output"];
      readonly yearsOfExperience: CodecTypes["pg/int4@1"]["output"];
    };
    readonly job: {
      readonly category:
        | "ENGINEERING"
        | "DESIGN"
        | "MARKETING"
        | "SALES"
        | "FINANCE"
        | "HUMAN_RESOURCES"
        | "CUSTOMER_SUPPORT"
        | "OPERATIONS";
      readonly company: CodecTypes["pg/text@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly description: CodecTypes["pg/text@1"]["output"];
      readonly experienceLevel: "ENTRY" | "MID" | "SENIOR";
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly isFeatured: CodecTypes["pg/bool@1"]["output"];
      readonly location: CodecTypes["pg/text@1"]["output"];
      readonly skills: ReadonlyArray<CodecTypes["pg/text@1"]["output"]>;
      readonly status: "DRAFT" | "PUBLISHED" | "CLOSED";
      readonly title: CodecTypes["pg/text@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly workplaceType: "ON_SITE" | "REMOTE" | "HYBRID";
    };
    readonly refreshToken: {
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly expiresAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly revokedAt: CodecTypes["pg/timestamptz-string@1"]["output"] | null;
      readonly tokenHash: CodecTypes["pg/text@1"]["output"];
      readonly userId: CodecTypes["pg/text@1"]["output"];
    };
    readonly user: {
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly email: CodecTypes["pg/text@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly passwordHash: CodecTypes["pg/text@1"]["output"];
      readonly role: "USER" | "ADMIN";
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly application: {
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly currentCompany: CodecTypes["pg/text@1"]["input"] | null;
      readonly currentRole: CodecTypes["pg/text@1"]["input"] | null;
      readonly education: CodecTypes["pg/text@1"]["input"] | null;
      readonly expectedSalary: CodecTypes["pg/int4@1"]["input"] | null;
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly jobId: CodecTypes["pg/text@1"]["input"];
      readonly noticePeriodDays: CodecTypes["pg/int4@1"]["input"] | null;
      readonly skills: ReadonlyArray<CodecTypes["pg/text@1"]["input"]>;
      readonly status: "APPLIED" | "REVIEWING" | "REJECTED" | "ACCEPTED";
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly userId: CodecTypes["pg/text@1"]["input"];
      readonly yearsOfExperience: CodecTypes["pg/int4@1"]["input"] | null;
    };
    readonly candidateProfile: {
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly currentCompany: CodecTypes["pg/text@1"]["input"] | null;
      readonly currentRole: CodecTypes["pg/text@1"]["input"] | null;
      readonly education: CodecTypes["pg/text@1"]["input"];
      readonly expectedSalary: CodecTypes["pg/int4@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly noticePeriodDays: CodecTypes["pg/int4@1"]["input"];
      readonly phone: CodecTypes["pg/text@1"]["input"];
      readonly skills: ReadonlyArray<CodecTypes["pg/text@1"]["input"]>;
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly userId: CodecTypes["pg/text@1"]["input"];
      readonly yearsOfExperience: CodecTypes["pg/int4@1"]["input"];
    };
    readonly job: {
      readonly category:
        | "ENGINEERING"
        | "DESIGN"
        | "MARKETING"
        | "SALES"
        | "FINANCE"
        | "HUMAN_RESOURCES"
        | "CUSTOMER_SUPPORT"
        | "OPERATIONS";
      readonly company: CodecTypes["pg/text@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly description: CodecTypes["pg/text@1"]["input"];
      readonly experienceLevel: "ENTRY" | "MID" | "SENIOR";
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly isFeatured: CodecTypes["pg/bool@1"]["input"];
      readonly location: CodecTypes["pg/text@1"]["input"];
      readonly skills: ReadonlyArray<CodecTypes["pg/text@1"]["input"]>;
      readonly status: "DRAFT" | "PUBLISHED" | "CLOSED";
      readonly title: CodecTypes["pg/text@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly workplaceType: "ON_SITE" | "REMOTE" | "HYBRID";
    };
    readonly refreshToken: {
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly expiresAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly revokedAt: CodecTypes["pg/timestamptz-string@1"]["input"] | null;
      readonly tokenHash: CodecTypes["pg/text@1"]["input"];
      readonly userId: CodecTypes["pg/text@1"]["input"];
    };
    readonly user: {
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly email: CodecTypes["pg/text@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly passwordHash: CodecTypes["pg/text@1"]["input"];
      readonly role: "USER" | "ADMIN";
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: "public";
        readonly kind: "postgres-schema";
        readonly entries: {
          readonly table: {
            readonly application: {
              columns: {
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly jobId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly yearsOfExperience: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: true;
                };
                readonly education: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly currentCompany: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly currentRole: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly expectedSalary: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: true;
                };
                readonly noticePeriodDays: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: true;
                };
                readonly skills: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "literal";
                    readonly value: DefaultLiteralValue<"pg/text@1", readonly []>;
                  };
                };
                readonly status: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "literal";
                    readonly value: DefaultLiteralValue<"pg/text@1", "APPLIED">;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                  readonly default: { readonly kind: "function"; readonly expression: "now()" };
                };
                readonly updatedAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["userId", "jobId"] }];
              indexes: readonly [
                {
                  readonly name: "application_jobId_idx_623c8f77";
                  readonly prefix: "application_jobId_idx";
                  readonly columns: readonly ["jobId"];
                  readonly unique: false;
                },
                {
                  readonly name: "application_userId_idx_a489d58a";
                  readonly prefix: "application_userId_idx";
                  readonly columns: readonly ["userId"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "application";
                    readonly columns: readonly ["userId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "user";
                    readonly columns: readonly ["id"];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "application";
                    readonly columns: readonly ["jobId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "job";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly candidateProfile: {
              columns: {
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly phone: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly education: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly yearsOfExperience: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly currentCompany: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly currentRole: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly expectedSalary: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly noticePeriodDays: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly skills: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                  readonly default: { readonly kind: "function"; readonly expression: "now()" };
                };
                readonly updatedAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["userId"] }];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "candidateProfile";
                    readonly columns: readonly ["userId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "user";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly job: {
              columns: {
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly title: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly description: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly company: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly location: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly workplaceType: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly category: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly experienceLevel: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly skills: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "literal";
                    readonly value: DefaultLiteralValue<"pg/text@1", readonly []>;
                  };
                };
                readonly status: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "literal";
                    readonly value: DefaultLiteralValue<"pg/text@1", "DRAFT">;
                  };
                };
                readonly isFeatured: {
                  readonly nativeType: "bool";
                  readonly codecId: "pg/bool@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "literal";
                    readonly value: DefaultLiteralValue<"pg/bool@1", false>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                  readonly default: { readonly kind: "function"; readonly expression: "now()" };
                };
                readonly updatedAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: "job_category_idx_f2600f8e";
                  readonly prefix: "job_category_idx";
                  readonly columns: readonly ["category"];
                  readonly unique: false;
                },
                {
                  readonly name: "job_experienceLevel_idx_88bcaa5e";
                  readonly prefix: "job_experienceLevel_idx";
                  readonly columns: readonly ["experienceLevel"];
                  readonly unique: false;
                },
                {
                  readonly name: "job_status_createdAt_idx_58610442";
                  readonly prefix: "job_status_createdAt_idx";
                  readonly columns: readonly ["status", "createdAt"];
                  readonly unique: false;
                },
                {
                  readonly name: "job_isFeatured_status_createdAt_idx_7db32ec7";
                  readonly prefix: "job_isFeatured_status_createdAt_idx";
                  readonly columns: readonly ["isFeatured", "status", "createdAt"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly refreshToken: {
              columns: {
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly tokenHash: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly expiresAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                };
                readonly revokedAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                  readonly default: { readonly kind: "function"; readonly expression: "now()" };
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["tokenHash"] }];
              indexes: readonly [
                {
                  readonly name: "refreshToken_userId_idx_a489d58a";
                  readonly prefix: "refreshToken_userId_idx";
                  readonly columns: readonly ["userId"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "refreshToken";
                    readonly columns: readonly ["userId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "user";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly user: {
              columns: {
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly passwordHash: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly role: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "literal";
                    readonly value: DefaultLiteralValue<"pg/text@1", "USER">;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                  readonly default: { readonly kind: "function"; readonly expression: "now()" };
                };
                readonly updatedAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["email"] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly ApplicationStatus: {
              readonly kind: "valueSet";
              readonly values: readonly ["APPLIED", "REVIEWING", "REJECTED", "ACCEPTED"];
            };
            readonly ExperienceLevel: {
              readonly kind: "valueSet";
              readonly values: readonly ["ENTRY", "MID", "SENIOR"];
            };
            readonly JobCategory: {
              readonly kind: "valueSet";
              readonly values: readonly [
                "ENGINEERING",
                "DESIGN",
                "MARKETING",
                "SALES",
                "FINANCE",
                "HUMAN_RESOURCES",
                "CUSTOMER_SUPPORT",
                "OPERATIONS",
              ];
            };
            readonly JobStatus: {
              readonly kind: "valueSet";
              readonly values: readonly ["DRAFT", "PUBLISHED", "CLOSED"];
            };
            readonly UserRole: {
              readonly kind: "valueSet";
              readonly values: readonly ["USER", "ADMIN"];
            };
            readonly WorkplaceType: {
              readonly kind: "valueSet";
              readonly values: readonly ["ON_SITE", "REMOTE", "HYBRID"];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  "roots" | "domain"
> & {
  readonly target: "postgres";
  readonly targetFamily: "sql";
  readonly roots: {
    readonly user: { readonly namespace: "public" & NamespaceId; readonly model: "User" };
    readonly candidateProfile: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "CandidateProfile";
    };
    readonly job: { readonly namespace: "public" & NamespaceId; readonly model: "Job" };
    readonly application: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "Application";
    };
    readonly refreshToken: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "RefreshToken";
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Application: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly jobId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly yearsOfExperience: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/int4@1" };
              };
              readonly education: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly currentCompany: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly currentRole: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly expectedSalary: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/int4@1" };
              };
              readonly noticePeriodDays: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/int4@1" };
              };
              readonly skills: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
                readonly many: true;
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
            };
            readonly relations: {
              readonly job: {
                readonly to: { readonly namespace: "public" & NamespaceId; readonly model: "Job" };
                readonly cardinality: "N:1";
                readonly on: {
                  readonly localFields: readonly ["jobId"];
                  readonly targetFields: readonly ["id"];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: "public" & NamespaceId; readonly model: "User" };
                readonly cardinality: "N:1";
                readonly on: {
                  readonly localFields: readonly ["userId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "application";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly userId: { readonly column: "userId" };
                readonly jobId: { readonly column: "jobId" };
                readonly yearsOfExperience: { readonly column: "yearsOfExperience" };
                readonly education: { readonly column: "education" };
                readonly currentCompany: { readonly column: "currentCompany" };
                readonly currentRole: { readonly column: "currentRole" };
                readonly expectedSalary: { readonly column: "expectedSalary" };
                readonly noticePeriodDays: { readonly column: "noticePeriodDays" };
                readonly skills: { readonly column: "skills" };
                readonly status: { readonly column: "status" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly updatedAt: { readonly column: "updatedAt" };
              };
            };
          };
          readonly CandidateProfile: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly phone: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly education: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly yearsOfExperience: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/int4@1" };
              };
              readonly currentCompany: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly currentRole: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly expectedSalary: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/int4@1" };
              };
              readonly noticePeriodDays: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/int4@1" };
              };
              readonly skills: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
                readonly many: true;
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: { readonly namespace: "public" & NamespaceId; readonly model: "User" };
                readonly cardinality: "N:1";
                readonly on: {
                  readonly localFields: readonly ["userId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "candidateProfile";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly userId: { readonly column: "userId" };
                readonly phone: { readonly column: "phone" };
                readonly education: { readonly column: "education" };
                readonly yearsOfExperience: { readonly column: "yearsOfExperience" };
                readonly currentCompany: { readonly column: "currentCompany" };
                readonly currentRole: { readonly column: "currentRole" };
                readonly expectedSalary: { readonly column: "expectedSalary" };
                readonly noticePeriodDays: { readonly column: "noticePeriodDays" };
                readonly skills: { readonly column: "skills" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly updatedAt: { readonly column: "updatedAt" };
              };
            };
          };
          readonly Job: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly description: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly company: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly location: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly workplaceType: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly category: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly experienceLevel: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly skills: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
                readonly many: true;
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly isFeatured: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/bool@1" };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
            };
            readonly relations: {
              readonly applications: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Application";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["jobId"];
                };
              };
            };
            readonly storage: {
              readonly table: "job";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly title: { readonly column: "title" };
                readonly description: { readonly column: "description" };
                readonly company: { readonly column: "company" };
                readonly location: { readonly column: "location" };
                readonly workplaceType: { readonly column: "workplaceType" };
                readonly category: { readonly column: "category" };
                readonly experienceLevel: { readonly column: "experienceLevel" };
                readonly skills: { readonly column: "skills" };
                readonly status: { readonly column: "status" };
                readonly isFeatured: { readonly column: "isFeatured" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly updatedAt: { readonly column: "updatedAt" };
              };
            };
          };
          readonly RefreshToken: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly tokenHash: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly expiresAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
              readonly revokedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: { readonly namespace: "public" & NamespaceId; readonly model: "User" };
                readonly cardinality: "N:1";
                readonly on: {
                  readonly localFields: readonly ["userId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "refreshToken";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly tokenHash: { readonly column: "tokenHash" };
                readonly userId: { readonly column: "userId" };
                readonly expiresAt: { readonly column: "expiresAt" };
                readonly revokedAt: { readonly column: "revokedAt" };
                readonly createdAt: { readonly column: "createdAt" };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly passwordHash: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
            };
            readonly relations: {
              readonly applications: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Application";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["userId"];
                };
              };
              readonly candidateProfile: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "CandidateProfile";
                };
                readonly cardinality: "1:1";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["userId"];
                };
              };
              readonly refreshTokens: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "RefreshToken";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["userId"];
                };
              };
            };
            readonly storage: {
              readonly table: "user";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly email: { readonly column: "email" };
                readonly name: { readonly column: "name" };
                readonly passwordHash: { readonly column: "passwordHash" };
                readonly role: { readonly column: "role" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly updatedAt: { readonly column: "updatedAt" };
              };
            };
          };
        };
        readonly enum: {
          readonly UserRole: {
            readonly codecId: "pg/text@1";
            readonly members: readonly [
              { readonly name: "USER"; readonly value: "USER" },
              { readonly name: "ADMIN"; readonly value: "ADMIN" },
            ];
          };
          readonly JobCategory: {
            readonly codecId: "pg/text@1";
            readonly members: readonly [
              { readonly name: "ENGINEERING"; readonly value: "ENGINEERING" },
              { readonly name: "DESIGN"; readonly value: "DESIGN" },
              { readonly name: "MARKETING"; readonly value: "MARKETING" },
              { readonly name: "SALES"; readonly value: "SALES" },
              { readonly name: "FINANCE"; readonly value: "FINANCE" },
              { readonly name: "HUMAN_RESOURCES"; readonly value: "HUMAN_RESOURCES" },
              { readonly name: "CUSTOMER_SUPPORT"; readonly value: "CUSTOMER_SUPPORT" },
              { readonly name: "OPERATIONS"; readonly value: "OPERATIONS" },
            ];
          };
          readonly JobStatus: {
            readonly codecId: "pg/text@1";
            readonly members: readonly [
              { readonly name: "DRAFT"; readonly value: "DRAFT" },
              { readonly name: "PUBLISHED"; readonly value: "PUBLISHED" },
              { readonly name: "CLOSED"; readonly value: "CLOSED" },
            ];
          };
          readonly ExperienceLevel: {
            readonly codecId: "pg/text@1";
            readonly members: readonly [
              { readonly name: "ENTRY"; readonly value: "ENTRY" },
              { readonly name: "MID"; readonly value: "MID" },
              { readonly name: "SENIOR"; readonly value: "SENIOR" },
            ];
          };
          readonly WorkplaceType: {
            readonly codecId: "pg/text@1";
            readonly members: readonly [
              { readonly name: "ON_SITE"; readonly value: "ON_SITE" },
              { readonly name: "REMOTE"; readonly value: "REMOTE" },
              { readonly name: "HYBRID"; readonly value: "HYBRID" },
            ];
          };
          readonly ApplicationStatus: {
            readonly codecId: "pg/text@1";
            readonly members: readonly [
              { readonly name: "APPLIED"; readonly value: "APPLIED" },
              { readonly name: "REVIEWING"; readonly value: "REVIEWING" },
              { readonly name: "REJECTED"; readonly value: "REJECTED" },
              { readonly name: "ACCEPTED"; readonly value: "ACCEPTED" },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: "public";
            readonly table: "application";
            readonly column: "id";
          };
          readonly onCreate: { readonly kind: "generator"; readonly id: "uuidv4" };
        },
        {
          readonly ref: {
            readonly namespace: "public";
            readonly table: "application";
            readonly column: "updatedAt";
          };
          readonly onCreate: { readonly kind: "generator"; readonly id: "timestampNow" };
          readonly onUpdate: { readonly kind: "generator"; readonly id: "timestampNow" };
        },
        {
          readonly ref: {
            readonly namespace: "public";
            readonly table: "candidateProfile";
            readonly column: "id";
          };
          readonly onCreate: { readonly kind: "generator"; readonly id: "uuidv4" };
        },
        {
          readonly ref: {
            readonly namespace: "public";
            readonly table: "candidateProfile";
            readonly column: "updatedAt";
          };
          readonly onCreate: { readonly kind: "generator"; readonly id: "timestampNow" };
          readonly onUpdate: { readonly kind: "generator"; readonly id: "timestampNow" };
        },
        {
          readonly ref: {
            readonly namespace: "public";
            readonly table: "job";
            readonly column: "id";
          };
          readonly onCreate: { readonly kind: "generator"; readonly id: "uuidv4" };
        },
        {
          readonly ref: {
            readonly namespace: "public";
            readonly table: "job";
            readonly column: "updatedAt";
          };
          readonly onCreate: { readonly kind: "generator"; readonly id: "timestampNow" };
          readonly onUpdate: { readonly kind: "generator"; readonly id: "timestampNow" };
        },
        {
          readonly ref: {
            readonly namespace: "public";
            readonly table: "refreshToken";
            readonly column: "id";
          };
          readonly onCreate: { readonly kind: "generator"; readonly id: "uuidv4" };
        },
        {
          readonly ref: {
            readonly namespace: "public";
            readonly table: "user";
            readonly column: "id";
          };
          readonly onCreate: { readonly kind: "generator"; readonly id: "uuidv4" };
        },
        {
          readonly ref: {
            readonly namespace: "public";
            readonly table: "user";
            readonly column: "updatedAt";
          };
          readonly onCreate: { readonly kind: "generator"; readonly id: "timestampNow" };
          readonly onUpdate: { readonly kind: "generator"; readonly id: "timestampNow" };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract["storage"]["namespaces"];
